### ISSUE TITLE
Broken date and time pickers

### ISSUE THREAD

**Issue by kasutajaimin** [Lootyhoof/opresto#1]
Date and time pickers enabled from _dom.forms.datetime_ config options and working properly with Pale Moon's default theme appear broken with **opresto** (and **pmopera**)
![image](https://user-images.githubusercontent.com/31406326/160014775-ede3c0f7-775c-4cd7-9649-a45cdd20cb21.png)
![image](https://user-images.githubusercontent.com/31406326/160014993-78ab6535-0f1f-4326-a94a-f23c454d620a.png)

 :gift_heart: Also thanks a million for keeping **opresto** going :gift_heart:

**Comment by Lootyhoof** [comment]
Thanks for this, I can confirm the same (across several themes). I'll work on it soon.

**Comment by Lootyhoof** [comment]
Fixed in `v2.8.0`. Updates for PMOpera (and other themes) will follow in due course.
